default: &default
  :url_shortener:
    :url_template: https://is.gd/create.php?format=simple&url=LONG_URL
  :heading_extractor:
    :tags:
      - h1
      - h2
      - h3

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
